#[path = "routes/docs/cli.rs"]
pub mod docs_cli;
#[path = "routes/docs/database.rs"]
pub mod docs_database;
#[path = "routes/docs/deployment.rs"]
pub mod docs_deployment;
#[path = "routes/docs/index.rs"]
pub mod docs_index;
#[path = "routes/docs/installation.rs"]
pub mod docs_installation;
#[path = "routes/docs/islands.rs"]
pub mod docs_islands;
#[path = "routes/docs/layout.rs"]
pub mod docs_layout;
#[path = "routes/docs/layouts.rs"]
pub mod docs_layouts;
#[path = "routes/docs/project_structure.rs"]
pub mod docs_project_structure;
#[path = "routes/docs/request.rs"]
pub mod docs_request;
#[path = "routes/docs/response.rs"]
pub mod docs_response;
#[path = "routes/docs/routing.rs"]
pub mod docs_routing;
#[path = "routes/docs/static_assets.rs"]
pub mod docs_static_assets;
#[path = "routes/docs/tailwind.rs"]
pub mod docs_tailwind;
#[path = "routes/docs/templates.rs"]
pub mod docs_templates;
#[path = "routes/index.rs"]
pub mod index;
#[path = "routes/layout.rs"]
pub mod layout;
#[path = "routes/llms.rs"]
pub mod llms;
