//! Builder module for creating deployable Rejoice applications.
//!
//! This module handles generating Dockerfiles and managing the build process
//! for Rejoice applications deployed to Fly.io.

/// Information about a Rejoice project structure.
#[derive(Debug)]
pub struct ProjectInfo {
    /// Whether the project has a client/ directory (SolidJS islands)
    pub has_client: bool,
    /// Whether the project uses a database (has migrations/ or .env with DATABASE_URL)
    pub has_database: bool,
    /// Whether the project has a public/ directory for static assets
    pub has_public: bool,
    /// The package name from Cargo.toml
    pub package_name: Option<String>,
    /// The port the app listens on (detected from main.rs)
    pub port: u16,
}

impl Default for ProjectInfo {
    fn default() -> Self {
        Self {
            has_client: false,
            has_database: false,
            has_public: false,
            package_name: None,
            port: 8080, // Rejoice default
        }
    }
}

/// Generates a Dockerfile for a Rejoice application.
///
/// This creates a multi-stage build that:
/// 1. Installs Rejoice CLI and Bun
/// 2. Runs `rejoice build --release` (handles both Rust and client assets)
/// 3. Creates a minimal runtime image
///
/// The `package_name` is used to find the correct binary in target/release/.
/// The `port` is the port the app listens on.
pub fn generate_dockerfile(
    package_name: &str,
    has_client: bool,
    has_db: bool,
    has_public: bool,
    port: u16,
) -> String {
    let db_setup = if has_db {
        r#"
# Create data directory for SQLite
RUN mkdir -p /data && chown -R nonroot:nonroot /data
VOLUME ["/data"]
ENV DATABASE_URL=sqlite:/data/app.db
"#
    } else {
        ""
    };

    let copy_client_assets = match (has_client, has_public) {
        (true, true) => {
            r#"
# Copy client assets
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/public /app/public
"#
        }
        (true, false) => {
            r#"
# Copy client assets
COPY --from=builder /app/dist /app/dist
"#
        }
        (false, true) => {
            r#"
# Copy public assets
COPY --from=builder /app/public /app/public
"#
        }
        (false, false) => "",
    };

    format!(
        r#"# Rejoice Application Dockerfile
# Auto-generated by Rejoice Cloud

# Build stage - need Rust 1.92+ for let chains used by Rejoice CLI
FROM rust:1.92-slim-bookworm AS builder
WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    curl \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Install Bun (for client builds)
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:$PATH"

# Install Rejoice CLI
RUN cargo install rejoice

# Copy project files
COPY . .

# Build with Rejoice (handles both Rust and client assets)
RUN rejoice build --release

# Runtime image
FROM debian:bookworm-slim AS runtime
WORKDIR /app

# Install runtime dependencies (curl for health checks)
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Create non-root user
RUN useradd -m -u 1000 nonroot
{db_setup}
# Copy binary
COPY --from=builder /app/target/release/{package_name} /app/app
{copy_client_assets}
# Set ownership
RUN chown -R nonroot:nonroot /app

USER nonroot

# Expose port
EXPOSE {port}

# Health check - just verify the server responds
HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 \
    CMD curl -f http://localhost:{port}/ || exit 1

# Run the app
CMD ["/app/app"]
"#,
        package_name = package_name,
        db_setup = db_setup,
        copy_client_assets = copy_client_assets,
        port = port,
    )
}

/// Generates a fly.toml configuration file for a Rejoice app.
pub fn generate_fly_toml(app_name: &str, has_db: bool, port: u16) -> String {
    let mounts = if has_db {
        r#"
[mounts]
  source = "data"
  destination = "/data"
"#
    } else {
        ""
    };

    format!(
        r#"# Fly.io configuration for {app_name}
# Auto-generated by Rejoice Cloud

app = "{app_name}"
primary_region = "iad"

[build]

[env]
  REJOICE_ENV = "production"

[http_service]
  internal_port = {port}
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  path = "/"
  timeout = "5s"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
{mounts}"#,
        app_name = app_name,
        port = port,
        mounts = mounts,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_dockerfile_minimal() {
        let dockerfile = generate_dockerfile("my-app", false, false, false, 8080);
        assert!(dockerfile.contains("FROM rust:1.92-slim-bookworm"));
        assert!(dockerfile.contains("FROM debian:bookworm-slim"));
        assert!(dockerfile.contains("EXPOSE 8080"));
        assert!(dockerfile.contains("rejoice build --release"));
        assert!(dockerfile.contains("target/release/my-app"));
        assert!(!dockerfile.contains("VOLUME"));
        assert!(!dockerfile.contains("COPY --from=builder /app/dist"));
        assert!(!dockerfile.contains("COPY --from=builder /app/public"));
    }

    #[test]
    fn test_generate_dockerfile_with_custom_port() {
        let dockerfile = generate_dockerfile("my-app", false, false, false, 3000);
        assert!(dockerfile.contains("EXPOSE 3000"));
        assert!(dockerfile.contains("curl -f http://localhost:3000/"));
    }

    #[test]
    fn test_generate_dockerfile_with_client() {
        let dockerfile = generate_dockerfile("my-app", true, false, false, 8080);
        assert!(dockerfile.contains("bun.sh/install"));
        assert!(dockerfile.contains("COPY --from=builder /app/dist"));
        assert!(!dockerfile.contains("COPY --from=builder /app/public"));
    }

    #[test]
    fn test_generate_dockerfile_with_client_and_public() {
        let dockerfile = generate_dockerfile("my-app", true, false, true, 8080);
        assert!(dockerfile.contains("bun.sh/install"));
        assert!(dockerfile.contains("COPY --from=builder /app/dist"));
        assert!(dockerfile.contains("COPY --from=builder /app/public"));
    }

    #[test]
    fn test_generate_dockerfile_with_db() {
        let dockerfile = generate_dockerfile("my-app", false, true, false, 8080);
        assert!(dockerfile.contains("VOLUME"));
        assert!(dockerfile.contains("/data"));
        assert!(dockerfile.contains("DATABASE_URL"));
    }

    #[test]
    fn test_generate_dockerfile_with_public_only() {
        let dockerfile = generate_dockerfile("my-app", false, false, true, 8080);
        assert!(dockerfile.contains("COPY --from=builder /app/public"));
        assert!(!dockerfile.contains("COPY --from=builder /app/dist"));
    }

    #[test]
    fn test_generate_fly_toml() {
        let toml = generate_fly_toml("my-app", true, 8080);
        assert!(toml.contains("app = \"my-app\""));
        assert!(toml.contains("[mounts]"));
        assert!(toml.contains("destination = \"/data\""));
        assert!(toml.contains("internal_port = 8080"));
    }

    #[test]
    fn test_generate_fly_toml_custom_port() {
        let toml = generate_fly_toml("my-app", false, 3000);
        assert!(toml.contains("internal_port = 3000"));
    }
}
