#[path = "routes/auth/github/callback.rs"]
pub mod auth_github_callback;
#[path = "routes/auth/github/index.rs"]
pub mod auth_github_index;
#[path = "routes/auth/logout.rs"]
pub mod auth_logout;
#[path = "routes/index.rs"]
pub mod index;
#[path = "routes/layout.rs"]
pub mod layout;
#[path = "routes/projects/[id]/delete.rs"]
pub mod projects_param_id_delete;
#[path = "routes/projects/[id]/deploy.rs"]
pub mod projects_param_id_deploy;
#[path = "routes/projects/[id]/deployments/[deployment_id]/index.rs"]
pub mod projects_param_id_deployments_param_deployment_id_index;
#[path = "routes/projects/[id]/deployments/[deployment_id]/logs.rs"]
pub mod projects_param_id_deployments_param_deployment_id_logs;
#[path = "routes/projects/[id]/index.rs"]
pub mod projects_param_id_index;
#[path = "routes/projects/[id]/settings/env/[env_id]/delete.rs"]
pub mod projects_param_id_settings_env_param_env_id_delete;
#[path = "routes/projects/[id]/settings/env.rs"]
pub mod projects_param_id_settings_env;
#[path = "routes/projects/[id]/settings/index.rs"]
pub mod projects_param_id_settings_index;
#[path = "routes/projects/index.rs"]
pub mod projects_index;
#[path = "routes/projects/new.rs"]
pub mod projects_new;
