#[path = "routes/about/index.rs"]
pub mod about_index;
#[path = "routes/index.rs"]
pub mod index;
#[path = "routes/layout.rs"]
pub mod layout;
#[path = "routes/users/[id].rs"]
pub mod users_param_id;
#[path = "routes/users/index.rs"]
pub mod users_index;
#[path = "routes/users/layout.rs"]
pub mod users_layout;
